filter_unfollowers = [
    'arianagrande', 'standwithus', 'ubisoft', 'hannahbrooke', 'coreymylchreest', 'joeyking', 'haifa.krayot',
    'gal.tamam', 'sharon.cohen.nails', 'omricosmetics', 'idf_confessions', 'mitgaisim',
    'hackeriot_org', 'unique_dresser', 'mialandau', 'mia_schem', 'manifestonnetflix', 'magshiparty',
    'khloekardashian', 'm_laradar', 'nails.veralina', 'yonatanvii', 'brothersbondbourbon', 'hadarezra_',
    'pazheller', 'daniel_moers', 'iansomerhalder', 'idf', 'justiceforclace', 'realsmoothie', 'venes.bs',
    'labeaute.israel', 'miss.israsor', 'hachvana', 'buddyringsil', 'talshemeshsol',
    'propelthemoon_photography', 'microsoft_rnd_israel', 'hackthebox', 'gal_gadot', 'shiri_nail_beauty',
    'avishag_nails470', 'shiran_gili', 'kyliejenner', 'eranswis', 'rotemnailss', 'elys_hutchinson',
    'shmoolik.b', 'adialtur_nails', 'news.0nline', 'thevampirediaries', '_leebiran_', 'emilydamari',
    'lin_buaron', 'claireholt', 'la_top1', 'candiceking', 'type_il', 'sabrinacarpenter', 'mrbeast',
    'lihi.banin.levi', 'shirlilevi1234', 'amitmizrachix', 'noaxben', 'dana_tenne', 'barakjon',
    'tal.tamam', 'ux.ui.dan', 'shelart_shop', 'paulwesley', 'pedi_meni_racheli', 'emmawatson',
    'dareordare.co.il', 'hapshutaofficial', 'dielenka', 'loren.mor', 'drweissplastic',
    'liel_mordechaev', 'yaniv._.shoshani', 'push.il', 'karin_abelman', 'promise.cosmetics.il',
    'abbeycowen', 'camila_cabello', 'danny_griffin_', 'noatishby', 'joshdallas', 'bridgertonnetflix',
    'elianatidhar', 'vanessa.rhd', 'selenagomez', 'pewdiepie', 'israel_bidur', 'blackboxtlv',
    'israsor', 'hental2o', 'nina', 'ameliezilber', 'scooterbraun', 'billieeilish',
    'elluchka_', 'nasa', 'confi_hitech', 'kol_hahayalim', 'hilarefael_',
    'pet_line_', 'pashutnotion', 'yosef.physio', 'nivshamli', 'global.online.il', 'israeliairforce',
    'moran_magar_moranails', 'lin.alfi', 'hilitoledano', 'itsmeleighton', 'mayash0r', 'miryam.segal',
    'arad.rubinshtein', 'kimdavary_designer', 'ami_p_hair', 'magshimim.next', 'briannehowey',
    '4ilorg', 'liyanoga_spam', 'orozer_cohen', 'pcgaming1998', 'maya_kislev', 'sssniperwolf',
    'yosephhaddad', 'stateofisrael', 'eden.sasi.hair', 'liyanoga.x', 'matthewdaddario', 'zetricky',
    'simoneashley', 'pishpeshuk', 'xsh1roox', 'noahschnapp', 'denistal84', 'ori_novik', 'shirahaas',
    'israel.business', 'shakeds_life', 'mika_zohar__', 'dana_kedem', 'yoteridf',
    'israel_bidur_gaming', 'louis_russell', 'cybereducationcenter', 'deal_cosmetics',
    'rapunzille_', 'sketchie_digital', 'omer.miran1', 'samaya_maayan_oz', 'natebuzz', 'natalydadon',
    'gelly_nails.by.miru', 'aline_cohenn', 'maayan_shatit_nlp', 'paz_flaysher', 'mor_malachi',
    'camholmess', 'edenbenzaken', 'or__leon', 'emilyfayemiller', 'taliaovadia1', 'endoisrael',
    'ellalee', 'noakirel', 'lady.confessions', 'kerenthelawyer', 'noykeynan',
    'vakscoffee', 'kat.mcnamara', 'simonebiles', 'madisonbeer', 'ah_jewels', 'may_arev', 'idanborulya']
